Traceback (most recent call last):
  File "<ipython-input-1-685898621652>", line 7, in <module>
    raise Exception('This is the error message.')
Exception: This is the error message.
Traceback (most recent call last):
  File "<ipython-input-1-685898621652>", line 7, in <module>
    raise Exception('This is the error message.')
Exception: This is the error message.
Traceback (most recent call last):
  File "<ipython-input-2-685898621652>", line 7, in <module>
    raise Exception('This is the error message.')
Exception: This is the error message.
Traceback (most recent call last):
  File "<ipython-input-3-685898621652>", line 7, in <module>
    raise Exception('This is the error message.')
Exception: This is the error message.
